version: "3"

services:
    # https://hub.docker.com/r/mysql/mysql-server
    mysql:
        container_name: dc-mysql
        env_file:
            - mysql.env
        image: mysql/mysql-server:latest
        networks:
            - nw-mysql
        ports:
            - 3306:3306
        restart: always
        tty: true
        volumes:
            - ./mysql-data:/var/lib/mysql
            - ./mysql-initdb.d:/docker-entrypoint-initdb.d/

networks:
    nw-mysql:
        driver: bridge
